name: Update README Index

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest  # Use an Ubuntu runner to execute the script
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This checks out your repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run the update_readme script
      run: |
        python Scripts/update_readme.py  # Run the script to update the README.md file

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'Automatically updated the repository index in README.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
